name: AddressSanitizer Leak Test

on: [push, pull_request]

jobs:
  asan-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure and Build with AddressSanitizer
        run: |
          cmake -S . -B build \
            -DCMAKE_C_COMPILER=cc \
            -DCMAKE_CXX_COMPILER=c++ \
            -DCMAKE_CXX_FLAGS="-fsanitize=address -g -O1" \
            -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run with AddressSanitizer
        run: |
          export ASAN_OPTIONS="verbosity=1:log_path=asan-log"
          
          if [ "${{ runner.os }}" = "Linux" ]; then
            export ASAN_OPTIONS="detect_leaks=1:$ASAN_OPTIONS"
          fi

          ./build/memory_leak 2>&1 | tee asan.out

          if ls asan-log.* 1>/dev/null 2>&1; then
            echo "--- AddressSanitizer log ---"
            cat asan-log.*
          else
            echo "No ASan log file found."
          fi
        shell: bash
